---

mirror_images:
  case_bundles:
  - name: bas
    inv: Setup
    registries:
    - host: registry.redhat.io
      user: "{{ lookup('env', 'REDHAT_IO_USER') }}"
      password: "{{ lookup('env', 'REDHAT_IO_ENTITLEMENT_KEY') }}"
    - host: registry.connect.redhat.com
      user: "{{ lookup('env', 'REDHAT_IO_USER') }}"
      password: "{{ lookup('env', 'REDHAT_IO_ENTITLEMENT_KEY') }}"
  - name: cert-manager
    inv: Setup
    registries: []
  - name: cso
    inv: Setup
    registries:
    - host: quay.io
      user: "{{ lookup('env', 'QUAY_IO_USER') }}"
      password: "{{ lookup('env', 'QUAY_IO_ENTITLEMENT_KEY') }}"
  - name: ocp
    inv: Setup
    registries:
    - host: quay.io
      user: "{{ lookup('env', 'QUAY_IO_USER') }}"
      password: "{{ lookup('env', 'QUAY_IO_ENTITLEMENT_KEY') }}"
  - name: mongodb
    inv: Setup
    registries:
    - host: quay.io
      user: "{{ lookup('env', 'QUAY_IO_USER') }}"
      password: "{{ lookup('env', 'QUAY_IO_ENTITLEMENT_KEY') }}"
  - name: ocs
    inv: Setup
    registries:
    - host: registry.redhat.io
      user: "{{ lookup('env', 'REDHAT_IO_USER') }}"
      password: "{{ lookup('env', 'REDHAT_IO_ENTITLEMENT_KEY') }}"
  - name: sbo
    inv: Setup
    registries: []
  catalogs:
